version: "3.8"

services:
  inventory-service:
    build: .
    container_name: inventory-service
    ports:
      - "3000:3000"   # host:container
    volumes:
      - ./cache:/usr/src/app/cache   # щоби кеш фото зберігався на хості
    command: ["node", "index.js", "--host", "0.0.0.0", "--port", "3000", "--cache", "./cache"]
